### ISSUE TITLE
Organize itens in separate files

### ISSUE THREAD

**Issue by YanMagale** [obetomuniz/awesome-webcomponents#4]
What do you think about  organize the itens in separate files ?

**Comment by obetomuniz** [comment]
Hmmm... It's a good idea, for each section? Or subsections too?

**Comment by obetomuniz** [comment]
@YanMagale :question:

**Comment by YanMagale** [comment]
Hi Beto, sorry for delay.

Yes, initially only in sections, and the extent to which the list is growing, use subsections.

**Comment by afonsopacifer** [comment]
@YanMagale :+1:

**Comment by obetomuniz** [comment]
@YanMagale What's the status of migration? 

:dancer:

**Comment by YanMagale** [comment]
Hi @obetomuniz . I was waiting his "OK" to send PR.

I will send this evening.
